---
- hosts: webserver
  vars:
  - warName: {{ warname }}
  - warRemotePath: /Spring_todo_app/

  tasks:
  - name: Download WAR to server
    command: wget http://example.com/file.war -O {{ warRemotePath }}/{{ warName }}
  
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest={{ tomcat_installation_directory}}/webapps/ROOT/ copy=no mode=0755 owner=tomcat7 group=tomcat7
    notify:
        - restart tomcat7
   
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat7
      service: name=tomcat7 state=restarted